apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-health-check-service
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer-health-check-service
  template:
    metadata:
      labels:
        app: consumer-health-check-service
    spec:
      containers:
      - name: consumer-health-check-service
        image: your-docker-username/consumer-health-check-service:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-health-check-service
  namespace: kafka
spec:
  selector:
    app: consumer-health-check-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
